### ISSUE TITLE
Any update on this?

### ISSUE THREAD

**Issue by popovae** [mbmccormick/hamachi-wdmycloud#1]
Hi,

Great thing you did! Is it possible to install it on the latest firmware?

**Comment by mbmccormick** [comment]
Thanks! I haven't been able to get this implementation working on the latest firmware due to the pagesize changes. However, there is a detailed guide on how to build the packages necessary for it here: https://community.wd.com/t/guide-building-packages-for-the-new-firmware-someone-tried-it/93382/7

I am no longer using Hamachi, so I haven't gotten around to trying to update this myself.
